### ISSUE TITLE
局ロゴ追加: テレビ新広島

### ISSUE THREAD

**Issue by yude** [SlashNephy/TvTestRPC#1]
* チャンネル名: テレビ新広島
* サービス ID: `47528`
* SVG: [gr_47528.zip](https://github.com/SlashNephy/TvTestRPC/files/6564517/gr_47528.zip) 
(GitHub Issues 上での svg ファイルのアップロードが不可能であったため、zip ファイルで固めてアップロードしています。)

**Comment by SlashNephy** [comment]
ありがとうございます！対応しました
