### ISSUE TITLE
カスタムロゴについて

### ISSUE THREAD

**Issue by hyper771** [SlashNephy/TvTestRPC#2]
（ほかの）地方局においてカスタムロゴを使いたいのですが、そのような仕様は追加できますでしょうか。

**Comment by SlashNephy** [comment]
おそらく既存のカスタムロゴを別の局で使いたいということだと思いますが、ini ファイルに任意に記述できる形で実装してみます。

**Comment by SlashNephy** [comment]
2.2 で当該機能を実装しました。
